services:
  app:
    ports:
      - ${UPLOADY_PORT:-8080}:8080
    volumes:
      - ${UPLOADY_UPLOADS_PATH:-uploads}:/var/www/html/uploads
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html
      SSL_MODE: "off"
    build:
      context: .
      args:
        USER_ID: ${UPLOADY_UID:-33}
        GROUP_ID: ${UPLOADY_GID:-33}
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: "uploady"
      MYSQL_USER: ${UPLOADY_MYSQL_USER:?error}
      MYSQL_PASSWORD: ${UPLOADY_MYSQL_PASS:?error}
      MYSQL_ROOT_PASSWORD: ${UPLOADY_MYSQL_ROOT_PASS:?error}
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
